#!/bin/bash

outer=1
for a in 1 2 3 4 5
do
echo "Iteratsia #$outer vneshnego zikla"
echo "-----------"
inner=1

for b in 1 2 3 4 5
do
echo "Iteraziya #$inner vlozhennogo zikla"
let "inner+=1"
done
let "outer+=1"
echo
done
