#!/bin/bash
echo "For"
for a in $@
do
let "i+=1"
echo "Param $i - $a"
done

echo "While"
i=1
while [ $i -le $# ]
do
echo "Param $i - ${!i}"
i=$((i+1))
done

echo "Until"
i=1
until [ $i -gt $# ]
do
echo "Param $i - ${!i}"
i=$((i+1))
done
